### ISSUE TITLE
raw/sarc.csv find user comments

### ISSUE THREAD

**Issue by guoxuxu** [NLPrinceton/SARC#3]
Hi~~~

I'm investigating sarcasm detection using your dataset and particularly I'm collecting users' information now. Please correct where I misunderstand. 

1. from SARC/2.0/README.txt, it reads that raw/sarc.csv contains sarcastic and non-sarcastic comments of authors in authors.json. I read the raw/sarc.csv dataset, the first example shows [0, "Yousa guys didn't upvote nothing!", 'BritishEnglishPolice',
        'worldpolitics', 3, 3, 0, '2009-01', 1233446126,
        "Mafia business 'equal' to 9% of Italian GDP", 'c07e6gg',
        '7tvvp']
I guess the sentence "Yousa guys didn't upvote nothing!" is a post, "BritishEnglishPolice" is an author made this post, "worldpolitics" is subrredit, "3, 3, 0" correspond to scores/ups/downs respectively, "2009-01" and "1233446397" are date and UTC. "Mafia business 'equal' to 9% of Italian GDP" is a comment on this post. And "c07e6gg" and "7tvvp" are sarc and non-sarc responses to this comment. But when I search the comments.json for "c07e6gg" and "7tvvp", it returned nothing.  Beside. what does "0" at the beginning mean? I see 0 appeared in many example. Could you help me understand this sarc.csv file? As my goal is to acquire some sarc and non-sarc comments or comments for a given author.

2.  I'm using SARC/2.0 main and pol datasets. I think SARC/2.0 should contain all those in SARC/1.0 and SARC/0.0, right?

Thank you very much!
Best regards

**Comment by nsaunshi** [comment]
Hello,

1a. I would recommend using raw/sequences.csv to get posts/comments and sarcastic and non-sarcastic responses to them. raw/sequences.csv contains comment ids that can be decoded using raw/comments.json. Refer to SARC/2.0/readme.txt for details on the format.

1b. In case you want to use raw/sarc.csv (which might contain more comments than sequences.csv), please refer to raw/key.csv for what the columns mean. Specifically, the first bit (the "0" you referred to) corresponds to the label of the comment, 0 is non-sarcastic and 1 is sarcastic. The final two ids are not responses to this comment, but the comment id and the parent id.

2. There are no containment guarantees. In fact due to more filters being applied, SARC 2.0 might even have fewer comments than 1.0 and 0.0

**Comment by guoxuxu** [comment]
Thank you very much.
